//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FilterLanguage.g4 by ANTLR 4.5.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ProgressOnderwijsUtils.FilterLanguage {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FilterLanguageParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.2")]
[System.CLSCompliant(false)]
public interface IFilterLanguageVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>AndCombined</c>
	/// labeled alternative in <see cref="FilterLanguageParser.combined"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndCombined([NotNull] FilterLanguageParser.AndCombinedContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OrCombined</c>
	/// labeled alternative in <see cref="FilterLanguageParser.combined"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrCombined([NotNull] FilterLanguageParser.OrCombinedContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryCriterium</c>
	/// labeled alternative in <see cref="FilterLanguageParser.criterium"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryCriterium([NotNull] FilterLanguageParser.UnaryCriteriumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryCriteriumWithColumn</c>
	/// labeled alternative in <see cref="FilterLanguageParser.criterium"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryCriteriumWithColumn([NotNull] FilterLanguageParser.BinaryCriteriumWithColumnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryCriteriumWithNumber</c>
	/// labeled alternative in <see cref="FilterLanguageParser.criterium"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryCriteriumWithNumber([NotNull] FilterLanguageParser.BinaryCriteriumWithNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NestedCombined</c>
	/// labeled alternative in <see cref="FilterLanguageParser.criterium"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNestedCombined([NotNull] FilterLanguageParser.NestedCombinedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FilterLanguageParser.unaryComparer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryComparer([NotNull] FilterLanguageParser.UnaryComparerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FilterLanguageParser.binaryComparer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryComparer([NotNull] FilterLanguageParser.BinaryComparerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FilterLanguageParser.columnName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumnName([NotNull] FilterLanguageParser.ColumnNameContext context);
}
} // namespace ProgressOnderwijsUtils.FilterLanguage
