<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../src/Common.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TieredCompilation>false</TieredCompilation>
    <StartupObject>ProgressOnderwijsUtilsBenchmarks.BenchmarkProgram</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="IncrementalMeanVarianceAccumulator" Version="1.0.0" />
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <ProjectReference Include="..\..\src\ProgressOnderwijsUtils\ProgressOnderwijsUtils.csproj" />
    <ProjectReference Include="..\..\test\ProgressOnderwijsUtils.Tests\ProgressOnderwijsUtils.Tests.csproj" />
  </ItemGroup>
</Project>
